input {
  udp {
    port => 5144
    type => "fortigate"
  }
}

filter {
  if [type] == "fortigate" {
    grok {
      match => { "message" => "%{SYSLOG5424PRI}%{GREEDYDATA:log_message}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "_LkL1dt8HldM21cMk*iF"
    ssl_certificate_verification => false
    index => "fortigate-logs-%{+YYYY.MM.dd}"
  }
}
